**Fonte:**
este material é uma tradução e adaptação dos notebooks: <br/> https://github.com/AutoGIS-2019/Exercise-1/blob/master/Exercise-1-problem-1-2.ipynb <br/> https://github.com/AutoGIS-2019/Exercise-1/blob/master/Exercise-1-problem-3-4.ipynb

# Exercício 1: trabalhando com objetos geométricos

Neste exercício vamos praticas como criar objetos usando o módulo Shapely e como encontrar diferentes atributos dessas geometrias. Vamos utilizar as funções aprendidas anteriormente para fazer diferentes operações.

## Problema 1: criando geometrias básicas

1. Crie uma função chamada `create_point_geom()` que recebe dois parâmetros (x_coord, y_coord). Função deve retornar um objeto `Point` do módulo Shapely. 

In [1]:
# import libraries
from shapely.geometry import Point, LineString, Polygon

def create_point_geom(x_coord, y_coord):
    return Point(x_coord, y_coord)

Demonstre o uso da função códificada na célula acima criando um objeto `Point`

In [2]:
point1 = create_point_geom(2.25, 5.2)
print(point1)

POINT (2.25 5.2)


2. Crie uma função chamada **`create_line_geom()`** que recebe uma lista de objetos `Point` como parâmetro chamado de **`points`** e retorna um objeto `LineString` contendo estes pontos. Em adição, você deve tomar cuidado para a função tratar alguns casos como:
 - Dentro da função, deve ser checado com `assert` se o parâmetro de entrada é uma **list**. Se outro objeto for enviado como parâmetro, deve ser retornado a seguinte mensagem de erro: `"Input should be a list!"`
 - Também deverá ser verificado com o `assert` se a lista de entrada contém pelo menos dois valores. Caso contrário, retorne uma mensagem de erro: `"LineString object requires at least two Points!"`

In [2]:
def create_line_geom(points):
    
    # Check if inputs is type list
    assert isinstance(points, (list)), "Input should be a list!"
    
    # Check that the list contains at least two values
    assert len(points) >= 2, "LineString object requires at least two Points!"
    
    return LineString([[point.x, point.y] for point in points])

Demonstre o uso da função acima criando um `LineString` com dois pontos: <br/> Point(45.2, 22.34) <br/> Point(100.22, -3.20)

In [4]:
point1 = Point(45.2, 22.34)
point2 = Point(100.22, -3.20)

line1 = create_line_geom([point1, point2])
print(line1)

LINESTRING (45.2 22.34, 100.22 -3.2)


3. Crie uma função chamada **`create_poly_geom()`** que recebe um parâmetro chamado de `coords`, que é uma lista de objetos `Point` e retorna um objeto `Polygon`.

 - Dentro da função, deve ser checado com `assert` se o parâmetro de entrada é uma **list**. Se outro objeto além de uma lista for enviado como parâmetro deve ser retornado a seguinte mensagem de erro: `"Input should be a list!"`
 - Também deverá ser verificado com `assert`se a lista de entrada contém pelo menos três valores. Caso contrário retorne uma mensagem de erro: `"Polygon object requires at least three Points!"`

In [3]:
Demonstre o uso da função acima criando um `LineString` com dois pontos: <br/> Point(45.2, 22.34) <br/> Point(100.22, -3.20)# REPLACE THE ERROR BELOW WITH YOUR OWN CODE
def create_poly_geom(points):
    
    # Check if inputs is type list
    assert isinstance(points, (list)), "Input should be a list!"
    
    # Check that the list contains at least two values
    assert len(points) >= 3, "LineString object requires at least three Points!"
    
    return Polygon([[point.x, point.y] for point in points])

SyntaxError: invalid syntax (<ipython-input-3-e1125c8457ab>, line 1)

Demonstre o uso da função acima criando um `Polygon` com três pontos: Point(45.2, 22.34), Point(100.22, -3.20) & Point(70.0, 10.20)

In [6]:
point1 = Point(45.2, 22.34)
point2 = Point(100.22, -3.20)
point3 = Point(70.0, 10.20)

poly1 = create_poly_geom([point1, point2, point3])
print(poly1)

POLYGON ((45.2 22.34, 100.22 -3.2, 70 10.2, 45.2 22.34))


## Problema 2: atributos das geometrias

1. Crie uma função chamada **`get_centroid()`** que possui um parâmetro chamado geom. A função deve receber qualquer tipo de objeto geométrico do modulo shapely e retornar o centróide dessa geométria. Em adição, você deve tomar cuidado para a função tratar alguns casos como:
 - Dentro da função, deve ser checado com assert se o parâmetro de entrada é um Shapely `Point`, `LineString` ou `Polygon`. Se outro objeto for enviado como parâmetro, deve ser retornado a seguinte mensagem de erro: `"Input should be a Shapely geometry!"`

In [7]:
Demonstre o uso da função acima criando um `LineString` com dois pontos: <br/> Point(45.2, 22.34) <br/> Point(100.22, -3.20)def get_centroid(geom):
    assert type(geom) in [Point, LineString, Polygon], "Input should be a Shapely geometry!"
    
    return geom.centroid

Demonstre o uso da função acima. Para isso você pode usar a função 'create_line_geom' codificada anteriormente. Crie uma linha com dois pontos: Point(45.2, 22.34) & Point(100.22, -3.20), e mostre o centróide. 

In [8]:
point1 = Point(45.2, 22.34) 
point2 = Point(100.22, -3.20)

line1 = create_line_geom([point1, point2])
centroid1 = get_centroid(line1)
print(centroid1)

POINT (72.71000000000001 9.57)


2. Crie uma função chamada **`get_area()`** que possui um parâmetro chamado polygon. A função deve receber um objeto `Polygon` do modulo shapely e retornar a área dessa geométria. Em adição, você deve tomar cuidado para a função tratar alguns casos como:
 - Dentro da função, deve ser checado com assert se o parâmetro de entrada é um Shapely `Polygon`. Se outro objeto for enviado como parâmetro, deve ser retornado a seguinte mensagem de erro: `"Input should be a Shapely Polygon -object!"`

In [9]:
def get_area(polygon):
    
    assert type(polygon) is Polygon, "Input should be a Shapely Polygon -object!"
    
    return polygon.area

Demonstre o uso da função acima. Para isso você pode usar a função 'create_poly_geom' codificada anteriormente. Crie um polygon com três pontos: Point(45.2, 22.34), Point(100.22, -3.20) & Point(70.0, 10.20), e mostre a área. 

In [10]:
point1 = Point(45.2, 22.34)
point2 = Point(100.22, -3.20)
point3 = Point(70.0, 10.20)

poly1 = create_poly_geom([point1, point2, point3])
get_area(poly1)

17.27539999999999

3. Crie uma função chamada **`get_length()`** que possui um parâmetro chamado geom. A função deve receber um objeto` LineString` ou `Polygon` do modulo shapely e retornar o comprimento da linha se for `LineString` ou o comrpimento do anel exterior se for um `Polygon`. Em adição, você deve tomar cuidado para a função tratar alguns casos como:
 - Dentro da função, deve ser checado com assert se o parâmetro de entrada é um Shapely `LineString` ou `Polygon`. Se outro objeto for enviado como parâmetro deve ser retornado a seguinte mensagem de erro: `"'geom' should be either LineString or Polygon!"`

In [11]:
def get_length(geom):
    
    assert type(geom) in [LineString, Polygon], "Input should be a Shapely Polygon -object!"
    
    return geom.length

Demonstre o uso da função acima. Você pode usar o mesmo polígono usado na questão anterior. 

In [12]:
point1 = Point(45.2, 22.34)
point2 = Point(100.22, -3.20)
point3 = Point(70.0, 10.20)

poly1 = create_poly_geom([point1, point2, point3])
get_length(poly1)

121.32841570092893

## Problema 3: lendo coordenadas de um arquivo e criando as geometrias.

Um problema comum em GIS é a situação em que você possui um conjunto de coordenadas em um arquivo, e você precisa mapeá-las. Em python existem diversas ferramentas para lidar com este tipo de situação, sendo possível ler dados de todos os tipos (como csv, txt, excel, gpx, databases e etc).

Vamos ver como podemos ler dados de um arquivo e criar objetos de pontos que podem ser salvos como um novo tipo. o Nosso dataset [travelTimes_2015_Helsinki.txt](data/travelTimes_2015_Helsinki.txt) consiste do tempo de viagem de lugares específicos na região de Helsinki. As primeiras quatros linhas podem ser vistas abaixo:

```
   from_id;to_id;fromid_toid;route_number;at;from_x;from_y;to_x;to_y;total_route_time;route_time;route_distance
   5861326;5785640;5861326_5785640;1;08:10;24.9704379;60.3119173;24.8560344;60.399940599999994;125.0;99.0;22917.6
   5861326;5785641;5861326_5785641;1;08:10;24.9704379;60.3119173;24.8605682;60.4000135;123.0;102.0;23123.5
   5861326;5785642;5861326_5785642;1;08:10;24.9704379;60.3119173;24.865102;60.4000863;125.0;103.0;23241.3
```
Como pode ser visto, existem muitas colunas diferentes nos nosso dados, mas as colunas importantes para o nosso problema são listadas aa seguir:

| Column | Description |
|--------|-------------|
| from_x | x-coordinate of the **origin** location (longitude) |
| from_y | y-coordinate of the **origin** location (latitude) |
| to_x   | x-coordinate of the **destination** location (longitude)|
| to_y   | y-coordinate of the **destination** location (latitude) |
| total_route_time | Travel time with public transportation at the route |

### Primeiro passo - Ler os dados

1. Leia o arquivo [data/travelTimes_2015_Helsinki.txt](data/travelTimes_2015_Helsinki.txt) em um variável **`dataframe`** usando Pandas. Depois mostre as cinco primeiras linhas do arquivo lido.
 - Lembre de verificar o separador dos dados.


In [15]:
import pandas as pd

def read_data(filename, separator):
    return pd.read_csv(filename, sep=separator)

filename = 'data/travelTimes_2015_Helsinki.txt'
separator = ';'
data = read_data(filename, separator)
data.head(5)

from_id    to_id      fromid_toid  route_number     at     from_x  \
0  5861326  5785640  5861326_5785640             1  08:10  24.970438   
1  5861326  5785641  5861326_5785641             1  08:10  24.970438   
2  5861326  5785642  5861326_5785642             1  08:10  24.970438   
3  5861326  5785643  5861326_5785643             1  08:10  24.970438   
4  5861326  5787544  5861326_5787544             1  08:10  24.970438   

      from_y       to_x       to_y  total_route_time  route_time  \
0  60.311917  24.856034  60.399941             125.0        99.0   
1  60.311917  24.860568  60.400014             123.0       102.0   
2  60.311917  24.865102  60.400086             125.0       103.0   
3  60.311917  24.869636  60.400159             129.0       107.0   
4  60.311917  24.842582  60.397478             118.0        92.0   

   route_distance  route_total_lines  
0         22917.6                2.0  
1         23123.5                2.0  
2         23241.3                2.0  
3         23534.2                2.0  
4         22428.2                2.0

### Segundo passo - Selecionar os dados
2. Selecione somente as seguintes colunas do DataFrame: **'from_x'**, **'from_y'**, **'to_x'**, **'to_y'** e armazene em um variável chamado **`data`**. Depois mostre somente as colunas do dataframe (.columns).

In [17]:
def take_coordinates(data):
    return data[['from_x', 'from_y', 'to_x', 'to_y']]

data = take_coordinates(data)
data.columns

Index(['from_x', 'from_y', 'to_x', 'to_y'], dtype='object')

### Terceiro passo - Criar pontos de origin e destino
3. Crie duas listas vazias para pontos, chamadas de **`orig_points`** e **`dest_points`**. Depois iterando em cada linha do seu DataFrame, adicione um objeto `Point` nas listas vazias criadas anteriormente, representando o ponto de origin (colunas `from_x` e `from_y`) e o ponto de destino (colunas `to_x` e `to_y`) respectivamente. 

In [18]:
orig_points = list()
dest_points = list()

for idx, row in data.iterrows():
    orig_points.append(Point(row['from_x'], row['from_y']))
    dest_points.append(Point(row['to_x'], row['to_y']))

print(orig_points[0:3])

[<shapely.geometry.point.Point object at 0x7f4d4d920750>, <shapely.geometry.point.Point object at 0x7f4d4d9206d0>, <shapely.geometry.point.Point object at 0x7f4d4d920790>]


### Quarto passo - Criar linha que representa movimento
4. Vamos criar um `LineString` que representa o movimento. Para isso, siga as seguitnes instruções:
 - Crie uma lista vazia chamada `Lines`
 - Itere sobre os pontos de origin e destino criados anterior e crie um objeto LineString.
     - Dica: Você pode utilizar a função `zip()` para percorrer várias listas ao mesmo tempo.  
 - Adicione a LineString na lista `Lines`
     

In [19]:
lines = list()

for origin, destiny in zip(orig_points, dest_points):
    lines.append(LineString((origin, destiny)))
    
print(lines[0:3])

[<shapely.geometry.linestring.LineString object at 0x7f4d4ce005d0>, <shapely.geometry.linestring.LineString object at 0x7f4d4ce00650>, <shapely.geometry.linestring.LineString object at 0x7f4d4ce006d0>]


### Quinto passo - Calcular o tamanho total
5. Crie uma variável chamada `total_length` e armazene a soma total das distâncias euclidianas de todas as LineStrings criadas anteriormente.
 - Dica: Você poderar iterar sobre as linhas e atualiza a variável com o tamanho.

In [20]:
total_length = sum([line.length for line in lines])

print("Total length of all lines is", total_length)

Total length of all lines is 3148.5707808651528


6. Para deixar o código mais reusável, reescreva em formato de função a criação do LineString e calculo do total das distâncias. Você pode copiar os códigos feitos anteriormente.
 - Nomeie as funções como desejar.
 - Dica: suas funções deve receber os pontos de origin e destino como listas.

In [21]:
def create_linestring(orig_points, dest_points):
    
    lines = list()
    for origin, destiny in zip(orig_points, dest_points):
        lines.append(LineString((origin, destiny)))
        
    return lines


def sum_length(lines):
       
    return sum([line.length for line in lines])

def take_total_length(orig_points, dest_points):
    lines = create_linestring(orig_points, dest_points)
    return sum_length(lines)


take_total_length(orig_points, dest_points)

3148.5707808651528

## Fim do exercício!

Você praticou com sucesso como as geometrias podem ser criadas em Python, realizou algumas operações básicas, carregou dados externos e fez operação sobre eles. Na próxima aula vamos usar as geometrias e operações ativamente. 